In [72]:
import numpy as np
import qutip as qt

# Pen and paper exercises:

## 1. calculate curcuits 

### a.
$$
    \ket{00} \overset{H\otimes H}{\rightarrow} \ket{++}
$$
### b. 
$$
    \ket{00} \overset{H\otimes H}{\rightarrow} \ket{++} \overset{CNOT}{\rightarrow} \ket{++}
$$
### c.
$$
    \ket{00} \overset{H\otimes H}{\rightarrow} \ket{++} \overset{CNOT}{\rightarrow} \ket{++} \overset{H\otimes H}{\rightarrow} \ket{00}
$$
### d.
$$
    \ket{00} 
    \overset{H\otimes H}{\rightarrow} \ket{++} 
    = \frac12\left(\ket{00} + \ket{+01} + \ket{10} + \ket{11}\right) \\\overset{I\otimes S}{\rightarrow} \frac12\left(\ket{00} + i\ket{01} + \ket{10} + i\ket{11}\right) 
    \overset{CNOT}{\rightarrow} \frac12\left(\ket{00} + i\ket{01} + \ket{11} + i\ket{10}\right)
$$
### e.  
$$
    \ket{00} 
    \overset{\cdots}{\rightarrow} \frac12\left(\ket{00} + i\ket{01} + \ket{11} + i\ket{10}\right)
    \overset{H\otimes H }{\rightarrow} \frac12\left(\ket{++} + i\ket{+-} + \ket{--} + i\ket{-+}\right) \\
    = \frac{1}{2}\bigg(
            \frac{1}{2}\Big(\ket{00}+\ket{01}+\ket{10}+\ket{11}\Big) + \frac12\Big(\ket{00}-\ket{10}-\ket{01}+\ket{11}\Big) + 
            \\
            \frac{i}{2}\Big(\ket{00} - \ket{01} + \ket{10} - \ket{11}\Big) + \frac{i}{2}\Big( \ket{00} + \ket{01} -\ket{10} - \ket{11}\Big)
            \bigg)
            \\
    = \frac{1}{2}\bigg((1+i)\ket{00} + (1-i)\ket{11}
        \bigg)
            
$$

In [ ]:
pp_res = ((1+1j)*qt.basis(4, 0) + (1-1j)*qt.basis(4, 3)).unit()

myin = qt.ket("00")
S = qt.gates.s_gate()
I = qt.identity(2)
H = qt.gates.hadamard_transform(1)

CNOT = qt.gates.cnot()
d = CNOT*qt.tensor(I, S)*qt.tensor(H, H)*myin
d.basis_expansion()

'(0.5+0j) |11> + 0.5j |10> + 0.5j |01> + (0.5+0j) |00>'

In [77]:
e = qt.tensor(H, H)*d
e.basis_expansion()

'(0.5-0.5j) |11> + (0.5+0.5j) |00>'

## 2. Decompose

In [89]:
Z = qt.sigmaz()
S = qt.gates.s_gate()
X = qt.sigmax()
Y = qt.sigmay()

H = qt.gates.hadamard_transform(1)
T = qt.gates.t_gate()
display(T)
display(H)

Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR, isherm=False
Qobj data =
[[1.        +0.j         0.        +0.j        ]
 [0.        +0.j         0.70710678+0.70710678j]]

Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dense, isherm=True
Qobj data =
[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]

In [ ]:
display(Z)
Z == T*T*T*T

Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR, isherm=True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]

True

In [166]:
display(S)
S == T*T

Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR, isherm=False
Qobj data =
[[1.+0.j 0.+0.j]
 [0.+0.j 0.+1.j]]

True

In [187]:
display(X)
H*T**4*H

Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR, isherm=True
Qobj data =
[[0. 1.]
 [1. 0.]]

Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dense, isherm=True
Qobj data =
[[4.26642159e-17 1.00000000e+00]
 [1.00000000e+00 4.26642159e-17]]

In [195]:
display(Y)
H*T**4*H*T**2

Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR, isherm=True
Qobj data =
[[0.+0.j 0.-1.j]
 [0.+1.j 0.+0.j]]

Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dense, isherm=False
Qobj data =
[[4.26642159e-17+0.00000000e+00j 0.00000000e+00+1.00000000e+00j]
 [1.00000000e+00+0.00000000e+00j 0.00000000e+00+4.26642159e-17j]]